{% set name = "lightkurve" %}
{% set version = "1.0b25" %}
{% set sha256 = "5a3e8c50220d846bb20b5c8cb219a4a750ded71176d0a45e1379634248362c64" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
    - astropy
    - astroquery
    - beautifulsoup4
    - matplotlib
    - numpy >=1.10  # required by autograd via oktopus
    - oktopus
    - pandas
    - bokeh >=1.0 # required for .interact() as of 1.0b23
    - pip
    - pytest-runner
    - python
    - requests
    - scipy
    - tqdm
  run:
    - astropy
    - astroquery
    - beautifulsoup4
    - matplotlib
    - {{ pin_compatible('numpy') }}
    - oktopus
    - bokeh
    - pandas
    - python
    - requests
    - scipy
    - tqdm

test:
  imports:
    - lightkurve

about:
  home: https://lightkurve.keplerscience.org/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'A beautiful package for astronomical flux time series analysis in Python'

  description: |
    The lightkurve Python package offers a beautiful and user-friendly way to
    analyze astronomical flux time series data, in particular the pixels and
    lightcurves obtained by NASA’s Kepler, K2, and TESS missions.
  doc_url: https://lightkurve.keplerscience.org/
  dev_url: https://github.com/KeplerGO/lightkurve

extra:
  recipe-maintainers:
    - gully
    - pkgw
